// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz3RHvXYcC8zgOWPJgo4CFoHc9ZlMxFqM',
    appId: '1:132102780539:web:741f9e73cf2199c3fe14de',
    messagingSenderId: '132102780539',
    projectId: 'nyota-e1dca',
    authDomain: 'nyota-e1dca.firebaseapp.com',
    storageBucket: 'nyota-e1dca.firebasestorage.app',
    measurementId: 'G-70GVGVTHJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4XK9hhmr8o-QZJ4hE9WqjGfb3Ts4d56M',
    appId: '1:132102780539:android:4de7f7d613a1d72ffe14de',
    messagingSenderId: '132102780539',
    projectId: 'nyota-e1dca',
    storageBucket: 'nyota-e1dca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHbRT263sZPnzP8tmD48PGB8YPvlSdNQk',
    appId: '1:132102780539:ios:55496a594b5b07effe14de',
    messagingSenderId: '132102780539',
    projectId: 'nyota-e1dca',
    storageBucket: 'nyota-e1dca.firebasestorage.app',
    iosBundleId: 'com.example.nyotaNewFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHbRT263sZPnzP8tmD48PGB8YPvlSdNQk',
    appId: '1:132102780539:ios:55496a594b5b07effe14de',
    messagingSenderId: '132102780539',
    projectId: 'nyota-e1dca',
    storageBucket: 'nyota-e1dca.firebasestorage.app',
    iosBundleId: 'com.example.nyotaNewFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz3RHvXYcC8zgOWPJgo4CFoHc9ZlMxFqM',
    appId: '1:132102780539:web:14e3ea81b229bfe6fe14de',
    messagingSenderId: '132102780539',
    projectId: 'nyota-e1dca',
    authDomain: 'nyota-e1dca.firebaseapp.com',
    storageBucket: 'nyota-e1dca.firebasestorage.app',
    measurementId: 'G-D26B37SRTG',
  );

}